# Generated by Django 5.0.3 on 2024-03-14 23:29

import django.db.models.deletion
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('fcountry', django_countries.fields.CountryField(max_length=2)),
                ('tcountry', django_countries.fields.CountryField(max_length=2)),
                ('departure_date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='Company.company')),
            ],
        ),
    ]
