# Generated by Django 5.0.3 on 2024-03-16 16:49

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layovers', to='Flights.flight')),
            ],
        ),
    ]
