# Generated by Django 5.0.3 on 2024-03-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0002_layover'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='seats_t',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='seats_v',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
