# Generated by Django 5.0.3 on 2024-03-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0003_flight_seats_t_flight_seats_v'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='image',
            field=models.ImageField(default=1, upload_to='flight/'),
            preserve_default=False,
        ),
    ]
