# Generated by Django 5.0.3 on 2024-03-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0004_flight_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
