# Generated by Django 5.0.3 on 2024-03-14 21:25

import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
