# Generated by Django 5.0.3 on 2024-03-14 23:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Used', 'Used'), ('Inactive', 'Inactive')], max_length=15)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Flights.flight')),
            ],
        ),
    ]
