# Generated by Django 5.0.3 on 2024-03-16 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
        ('Tickets', '0002_alter_ticket_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rank',
            field=models.CharField(choices=[('Tourist', 'Tourist'), ('VIP', 'VIP')], default='Tourist', max_length=10),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(choices=[('Active', 'Active'), ('Used', 'Used'), ('Inactive', 'Inactive')], default='Active', max_length=15)),
                ('date', models.DateField()),
                ('days', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Hotel.hotel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
