# Generated by Django 5.0.3 on 2024-03-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0003_ticket_rank_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
