# Generated by Django 5.0.3 on 2024-03-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0004_ticket_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
