# Generated by Django 5.0.3 on 2024-04-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0005_booking_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='code',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='code',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Used', 'Used'), ('Inactive', 'Inactive')], default='Inactive', max_length=15),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.CharField(choices=[('Active', 'Active'), ('Used', 'Used'), ('Inactive', 'Inactive')], default='Inactive', max_length=15),
        ),
    ]
